export const ACTIVE_LOAN_STATUSES = [
  "DRAFT",
  "SUBMITTED",
  "PENDING_RISK",
  "PENDING_APPROVAL",
  "APPROVED",
  "PENDING_CONTRACT",
  "CONTRACT_SIGNED",
  "CONTRACTED",
  "PENDING_DISBURSEMENT",
  "DISBURSED",
  "OVERDUE",
] as const;

export const TERMINAL_LOAN_STATUSES = [
  "REJECTED",
  "SETTLED",
  "COMPLETED",
  "CANCELLED",
] as const;

export const OPEN_DISBURSEMENT_STATUSES = ["PENDING", "PAID"] as const;

export const OPEN_FUNDER_WITHDRAWAL_STATUSES = ["PENDING", "APPROVED"] as const;
